services:

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: heladeria
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/data/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      retries: 5

  backend:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"

  tests:
    build: .
    command: pytest tests/ -v --alluredir=tests/reports/allure-results
    depends_on:
      - backend
    volumes:
      - ./tests/reports:/app/tests/reports

volumes:
  postgres_data:
